'use strict';
const questions = [
 {q:'ما عاصمة المملكة العربية السعودية؟',a:['جدة','الرياض','الدمام'],c:1,why:'الرياض هي عاصمة المملكة العربية السعودية.'},
 {q:'أين يوجد المسجد الحرام؟',a:['مكة المكرمة','الرياض','المدينة المنورة'],c:0,why:'المسجد الحرام في مكة المكرمة، وفيه الكعبة المشرفة.'},
 {q:'أي معلم يوجد في المدينة المنورة؟',a:['قصر المصمك','المسجد الحرام','المسجد النبوي'],c:2,why:'المسجد النبوي في المدينة المنورة.'},
 {q:'من وحّد المملكة العربية السعودية؟',a:['الملك عبدالعزيز','الإمام محمد بن سعود','الملك فيصل'],c:0,why:'وحّد الملك عبدالعزيز المملكة، وأُعلن اسمها عام ١٩٣٢م.'},
 {q:'بماذا بُنيت كثير من البيوت في نجد قديمًا؟',a:['بالزجاج','بالبلاستيك','بالطين'],c:2,why:'الطين من مواد بناء البيوت التراثية في نجد.'},
 {q:'ما عاصمة الدولة السعودية الأولى؟',a:['جدة','الدرعية','الدمام'],c:1,why:'كانت الدرعية عاصمة الدولة السعودية الأولى.'},
 {q:'ما المناسبة التي توافق ٢٣ سبتمبر؟',a:['يوم التأسيس','اليوم الوطني','يوم المعلم'],c:1,why:'اليوم الوطني في ٢٣ سبتمبر، ويوم التأسيس في ٢٢ فبراير.'},
 {q:'أي وسيلة نقل تربط مكة المكرمة بالمدينة المنورة؟',a:['قطار الحرمين','السفينة','الدراجة'],c:0,why:'قطار الحرمين السريع يربط مكة المكرمة بالمدينة المنورة مرورًا بجدة.'},
 {q:'قالت سارة: نحافظ على المباني التراثية لأنها تعرّفنا بتاريخ وطننا. هل كلامها صحيح؟',a:['نعم، صحيح','لا، غير صحيح'],c:0,why:'المباني التراثية تساعدنا على التعرف إلى حياة الأجداد وتاريخ وطننا.'},
 {q:'زرتَ معلمًا سياحيًا، فأين تضع بقايا طعامك؟',a:['على الأرض','خلف أحد الجدران','في سلة النفايات'],c:2,why:'نضع النفايات في السلة لنحافظ على نظافة وطننا وجماله.'}
];
const root=document.getElementById('quiz-app');
let index=0,score=0,answered=false,answers=[];
const ar=n=>n.toLocaleString('ar-SA');
function welcome(){root.innerHTML='<div class="quiz-welcome"><div class="big-star" aria-hidden="true">★</div><h3>هل أنت مستعد لاكتشاف ما تعلمته؟</h3><p>اختر إجابة واحدة في كل سؤال.<br>لا يوجد وقت محدد، ولكل إجابة صحيحة نجمة.</p><button class="button gold" id="start">ابدأ المسابقة</button></div>';document.getElementById('start').onclick=start;}
function start(){index=0;score=0;answers=[];render();}
function render(){answered=false;const q=questions[index];root.innerHTML='<div class="quiz-meta"><span>السؤال '+ar(index+1)+' من '+ar(questions.length)+'</span><span>نجومك: '+ar(score)+' ★</span></div><progress class="quiz-progress" value="'+index+'" max="10" aria-label="تقدم المسابقة"></progress><h3 class="quiz-question" tabindex="-1">'+q.q+'</h3><div class="options" role="group" aria-label="الإجابات">'+q.a.map((a,i)=>'<button class="option" data-answer="'+i+'"><span class="option-letter">'+['أ','ب','ج'][i]+'</span><span>'+a+'</span></button>').join('')+'</div><div id="feedback" aria-live="polite" aria-atomic="true"></div><div id="next-row" class="next-row"></div>';root.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.answer)));root.querySelector('h3').focus({preventScroll:true});}
function choose(choice){if(answered)return;answered=true;const q=questions[index],correct=choice===q.c;answers.push(choice);if(correct)score++;root.querySelectorAll('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.c){b.classList.add('correct');b.setAttribute('aria-label',q.a[i]+'، الإجابة الصحيحة');}else if(i===choice)b.classList.add('wrong');});root.querySelector('.quiz-meta').lastElementChild.textContent='نجومك: '+ar(score)+' ★';root.querySelector('progress').value=index+1;document.getElementById('feedback').innerHTML='<div class="feedback"><strong>'+(correct?'أحسنت! حصلت على نجمة ★':'محاولة طيبة، لنتعلم معًا')+'</strong><p>'+q.why+'</p></div>';document.getElementById('next-row').innerHTML='<button class="button" id="next">'+(index===questions.length-1?'شاهد النتيجة':'السؤال التالي ←')+'</button>';document.getElementById('next').onclick=()=>{index++;if(index<questions.length)render();else result();};}
function result(){root.innerHTML='<div class="result"><div class="result-score">'+ar(score)+' / '+ar(questions.length)+'</div><h3 tabindex="-1">'+(score>=8?'رائع يا مستكشف الوطن!':'أحسنت إكمال الرحلة!')+'</h3><p>'+(score>=8?'تعرفت إلى وطنك ومعالمه، ونجومك ثمرة تعلمك.':'تعلمت اليوم معلومات جديدة. راجع الإجابات، ثم حاول مرة أخرى.')+'</p><button class="button gold" id="restart">ألعب مرة أخرى</button><a class="button secondary" href="#places">أراجع معالم وطني</a></div><details class="review"><summary>مراجعة إجاباتي</summary><ol>'+questions.map((q,i)=>'<li><strong>'+q.q+'</strong><br>'+(answers[i]===q.c?'✓ إجابة صحيحة':'إجابتك: '+q.a[answers[i]])+'<br>'+q.why+'</li>').join('')+'</ol></details>';document.getElementById('restart').onclick=start;root.querySelector('h3').focus({preventScroll:true});}
welcome();
